const Medications = [
  'Acetazolamide',
  'Amantadine',
  'Aptiom',
  'Brivaracetam',
  'Briviact',
  'Carbamazepine',
  'Carbatrol',
  'Cerebyx',
  'Clobazam',
  'Clonazepam',
  'Clorazepate',
  'Depakote',
  'Depakote ER',
  'Depakote Sprinkles',
  'Diazepam',
  'Dilantin',
  'Divalproex Sodium',
  'Elepsia XR',
  'Epitol',
  'Eprontia',
  'Eslicarbazepine',
  'Ethosuximide',
  'Felbamate',
  'Felbatol',
  'Fosphenytoin',
  'Fycompa',
  'Gabapentin',
  'Gabitril',
  'Keppra',
  'Keppra XR',
  'Klonopin',
  'Lacosamide',
  'Lamictal',
  'Lamictal CD',
  'Lamictal ODT',
  'Lamictal XR',
  'Lamotrigine',
  'Levetiracetam',
  'Lorazepam',
  'Lyrica',
  'Motpoly XR',
  'Mysoline',
  'Neurontin',
  'Oxcarbazepine',
  'Oxtellar XR',
  'Perampanel',
  'Phenobarbital',
  'Phenytek',
  'Phenytoin Sodium',
  'Phenytoin',
  'Pregabalin',
  'Primidone',
  'Qudexy XR',
  'Roweepra',
  'Roweepra XR',
  'Rufinamide',
  'Sabril',
  'Spritam',
  'Subvenite',
  'Tegretol',
  'Tegretol XR',
  'Tiagabine',
  'Topamax',
  'Topiramate',
  'Trileptal',
  'Trokendi XR',
  'Valproate Sodium',
  'Valproic Acid',
  'Vigabatrin',
  'Vimpat',
  'Zonisamide',
];

// Medication List:
// https://www.drugs.com/condition/epilepsy.html?sort=drug&order=asc&page_number=3

export default Medications;
